name: Deploy Complex app to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: multi-cluster # TODO: update to cluster name
  GKE_ZONE: us-west1-a # TODO: update to cluster zone

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Log in to Docker CLI
      - name: Docker login
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Build and test multi-client image
      - name: Run Tests on Dev Image
        run: |-
          docker build -t noahapplegate/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true noahapplegate/react-test npm test

      # Build images and push to DockerHub
      - name: Build Images
        run: |-
          docker build -t noahapplegate/multi-client ./client
          docker build -t noahapplegate/multi-server ./server
          docker build -t noahapplegate/multi-worker ./worker

      - name: Push Images
        run: |-
          docker push noahapplegate/multi-client
          docker push noahapplegate/multi-server
          docker push noahapplegate/multi-worker

      # Deploy sample image to the GKE cluster
      - name: Deploy to GKE
        run: |-
          kubectl apply -f k8s
          kubectl get services -o wide
